### ISSUE TITLE
Make Slackbot Fail Silently

### ISSUE THREAD

**Issue by andela-anandaa** [scrapinghub/slackbot#105]
Is there a way to make a Slackbot fail silently without showing the end-user the stack-trace, e.g.
<img width="901" alt="screen shot 2016-08-13 at 1 50 01 pm" src="https://cloud.githubusercontent.com/assets/13568167/17642807/27e9f084-615d-11e6-9d7e-1971530c742c.png">

**Comment by jsargiot** [comment]
I might be wrong, but the only way to avoid showing tracebacks to users is to set [ERRORS_TO](https://github.com/lins05/slackbot#send-all-tracebacks-directly-to-a-channel-group-or-user) to send tracebacks to another channel/user/group.

Or you could wrap all your commands in a try, except and respond that command failed.

**Comment by rob-gonz** [comment]
@jsargiot is correct.  To be more specific, though, it is only the stack trace that will not be displayed in the slackbot response when using ERRORS_TO in the slackbot_settings.py. 

But,

> [temp] I had a problem handling "what is the temperature at Valhalla"

will still be displayed in response to the message "what is the temperature in Valhalla".  The stack trace will be then sent to the channel or user set in ERRORS_TO.

**Comment by andela-anandaa** [comment]
@jsargiot @THEANONYMOU5 - Thanks, makes sense!
