### ISSUE TITLE
Local File Inclusion Vulernarability in file upload  feature/example

### ISSUE THREAD

**Issue by maus-** [scrapinghub/slackbot#106]
You can arbitrarily upload any file on the host of the slackbot. IE !upload ../../../../etc/passwd or get it to drop sensitive config files.

**Comment by maus-** [comment]
You really should scope what folder that contains data to be uploaded to mitigate this.

**Comment by roperi** [comment]
Good point Although I think upload.py should be taken as an example. Nevertheless it should be pointed out at least in the comments of the function.
