### ISSUE TITLE
Ability to upload files based on "content", not "file" from filesystem

### ISSUE THREAD

**Issue by tehranian** [scrapinghub/slackbot#108]
Via https://api.slack.com/methods/files.upload

It'd be great if one could upload a text snippet via the "content" parameter of the upload API, and not have to read a file from disk. Alternatively, if the API supported reading from a file handle, then one could use https://docs.python.org/2/library/stringio.html or a filesystem file, as needed.

**Comment by willguxy** [comment]
Looks that this one is implemented already
https://github.com/lins05/slackbot/blob/9063de0b179acfe90b66903e5cef6a360081aaab/slackbot/slackclient.py#L132

should the issue ticket be closed?

**Comment by tehranian** [comment]
Oh nice, I would agree. I think this issue can be closed.
