### ISSUE TITLE
Get channel_id from message.

### ISSUE THREAD

**Issue by olanystrom** [scrapinghub/slackbot#11]
Is it possible to get the channel from the incoming message according to https://api.slack.com/events/message ?

I want to filter actions on channels.

**Comment by gpailler** [comment]
Currently, you can retrieve the channel id using

```
@listen_to('.+')
def catchall(message):
  print(message.body['channel'])
```

But please note it's the internal slack channel id, not the displayed name

**Comment by josegonzalez** [comment]
This can probably be closed.
