### ISSUE TITLE
Is it possible for slackbot to listen to external events and report it back to user? 

### ISSUE THREAD

**Issue by roperi** [scrapinghub/slackbot#114]
For instance, say slackbot listens to some external API live weather report. Then bot receives from the API a severe thunderstorm warning in an area that affects team. Could it be possible for the bot to send a warning to user or channel? Thanks in advance!

**Comment by rob-gonz** [comment]
+1  I am looking for this functionality as well.  I have many repositories and I would like to send a public update for every post_update hook call.

Edit:  This Issue #114 may be a duplicate of Issue #92, #54, #89; in a way.  From my understanding of the threads none have been pulled and all are waiting to be pulled.  Looks like #92 is the best candidate.

**Comment by roperi** [comment]
@THEANONYMOU5 

Unless I'm wrong it looks like the slackclient RTM doesn't support this. As a workaround I'm using [Incoming Webhooks](https://api.slack.com/incoming-webhooks) which let me send direct messages triggered by my own events directly to channels or usernames. Thing is messages are send via the official Slack's slackbot (not via our own slackbots).

**Comment by roperi** [comment]
So I'm closing this because according to what I have read Incoming Webhooks is a separate custom integration.

**Comment by roperi** [comment]
@THEANONYMOU5 

Oh. I didn't read your EDIT. I'll test how #92 works.
