### ISSUE TITLE
How to remove the prefixed "@user" text that shows up when bot replies to listen_to ?

### ISSUE THREAD

**Issue by roperi** [scrapinghub/slackbot#119]
Use case:

A visitor lands on website and from a chat widget asks a question about a product. The website chat widget status is monitored by incoming webhooks who in turn can post as a bot in public channels . So when visitor question is detected, it is captured and then forwarded to a specific public channel where anyone in the sales team (or even the slackbot) can read the question and answer it. 

My current setup is that when an incoming webhook bot message is posted in a public channel the slackbot posts -if no other team member is online-  an pre-defined answer based on the question. Problem is the reply starts with the "@user" prefix meaning is directed to a specific team member. How can I get rid of this prefix?.Thanks!

**Comment by roperi** [comment]
I solved this replying with the slacker client. Closing issue.

**Comment by jsargiot** [comment]
You could also use `message.send` instead of `message.reply` and it won't add the `@user` part.

**Comment by roperi** [comment]
Many thanks @jsargiot ! Didn't thought of that!
