### ISSUE TITLE
How to obtain Displayed channel and user names

### ISSUE THREAD

**Issue by drislands** [scrapinghub/slackbot#122]
Not sure if this obviously doable or obviously not doable, but is there a method to convert the user/channel ID gotten from message.body['channel']/['user'] into the displayed name when the bot's response reaches Slack?

**Comment by lukeconvertdigital** [comment]
```python
user    = message.channel._client.users[message.body['user']]
channel = message.channel._client.channels[message.body['channel']]

display_name = user['name']
first_name = user['first_name']

channel_name = channel['name']
```

**Comment by lins05** [comment]
Answered by @helloitsluke
