### ISSUE TITLE
@default_handler falls with excpetion

### ISSUE THREAD

**Issue by evasyuk** [scrapinghub/slackbot#127]
> Traceback (most recent call last):  File "/Library/Python/2.7/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler    func(Message(self._client, msg), *args) TypeError: default_handler() takes exactly 2 arguments (1 given)

It was working when I tried "Hello, ping!" few days ago, but after finishing real logic implementation I got that error.

I have no idea why do I have this problem, but it would be very nice if someone would help to handle this problem!

**Comment by lins05** [comment]
Can you show your code snippet for your default handler function?

**Comment by evasyuk** [comment]
Sorry, my bad - the problem was in the way I've tried to use decorators: they was used inside the custom wrapper class(but has to be only decorator for dedicated methods in the file without any class-wrappers)
