### ISSUE TITLE
Library does not support non-English characters

### ISSUE THREAD

**Issue by evasyuk** [scrapinghub/slackbot#129]
When library receives text in russian bot fails to resolve msg at (line 49 in dispatcher.py) 

> def _dispatch_msg_handler(self, category, msg):
>     pass

with error:

`UnicodeEncodeError: 'ascii' codec can't encode characters in position 44-47: ordinal not in range(128)`

**Comment by lins05** [comment]
Can you show the full traceback? I think we have unicode support covered in the tests https://github.com/lins05/slackbot/blob/b105feb22ef88d6950b6dbd6444d3518bea883bb/tests/functional/test_functional.py#L179-L188

**Comment by vyahhi** [comment]
@lins05 the following doesn't work:
```python
@respond_to('привет', re.IGNORECASE)
def hello(message):
    message.react('wave')
```
