### ISSUE TITLE
Quit slackbot from within a plugin

### ISSUE THREAD

**Issue by Omertron** [scrapinghub/slackbot#131]
I'd like to have an auto update routine for my plugin bot.

I have written a wrapper script around the "run.py" script to allow the autoupdate to pull from github when the bot exits before restarting the bot again.

However, I can't find a way to initiate a shutdown from within the bot.

Is there a way to do this?

**Comment by jlowin** [comment]
You can use `os._exit()` to force the process to quit without raising an error
