### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by josegonzalez** [scrapinghub/slackbot#150]
There have been a few changes since the last release, would it be possible to get another? :)

**Comment by jtatum** [comment]
It's on my to-do list 😄

**Comment by josegonzalez** [comment]
I'll buy you a pizza (up to 2 toppings) if you can get to it this week :)

**Comment by jtatum** [comment]
It's done, no pizza required 😉

**Comment by jtatum** [comment]
Just kidding, the push code is broken. Let me see if I can fix it and try again.

**Comment by jtatum** [comment]
0.5.1 is available on PyPi.
