### ISSUE TITLE
recognizing changed situation 

### ISSUE THREAD

**Issue by sthkindacrazy** [scrapinghub/slackbot#155]
when a new member is added to a slack, slackbot does not recognize the situation and the order of a new member does not work for the slackbot.

How can I deal with this point? Is there any way to refresh the channel, user - info to made slackbot?

**Comment by jtatum** [comment]
hi @sthkindacrazy,

The current development version of slackbot resolves this issue. We're a little behind on releasing an update, but if you pull down the source code here, you can use setup.py to install the module into a virtualenv or create a source or binary dist. Hopefully, you'll see version 0.5.0 on pypi soon.
