### ISSUE TITLE
Message.reply & message.post: URLs within angle brackets are not recognized

### ISSUE THREAD

**Issue by janik6n** [scrapinghub/slackbot#156]
I would like to format my URLs within responses as follows:
`message.reply('This is a demo message containing a link to <https://google.com|Google>.')`
This is described in Slack API docs https://api.slack.com/docs/message-formatting#linking_to_urls.

The result is "just text" with angle brackets and all in Slack, with no active/clickable hyperlink.

I tried to post the same message directly from slacker (0.9.50), and it works as expected.

Is there something in the message formatting which I keep missing, of have I found a bug?

I run this within virtualenv:
- Python 3.6.2
- Slackbot 0.4.1

**Comment by jtatum** [comment]
`message.reply` doesn't support sending formatted messages - it uses the RTM channel which specifically doesn't support this for bot users. For sending formatted messages, you should use `message.reply_webapi`, which uses slacker's (and slack's) chat.post_message call and supports formatting, attachments, etc.

**Comment by janik6n** [comment]
Thanks for the quick response! I totally missed that.
