### ISSUE TITLE
Threads release?

### ISSUE THREAD

**Issue by IanMitchell** [scrapinghub/slackbot#165]
Was curious if there was a release timeline for the `in_threads` message option? Seems to still not be up on pypi, was curious if there were plans to release it soon 😃 

https://github.com/lins05/slackbot/issues/136#issuecomment-320355349

**Comment by jtatum** [comment]
Hi Ian,

That was in 0.5.0. Current version on PyPI is 0.5.1. Make sure you update all dependencies - it depends on slacker >= 0.9.50.

**Comment by IanMitchell** [comment]
Huh, interesting. I'm getting the same error on 0.5.1 and slacker 0.9.6. Looking into it more now

**Comment by jtatum** [comment]
Sounds like your slacker version is way too old. Need to be 0.9.50. 0.9.60 is the latest release, but 0.9.6 would be pretty out of date. Just to be sure, what is the exact error you're getting?

**Comment by IanMitchell** [comment]
Oops, dropped a zero - it is 0.9.60,  my bad. I *think* it's a test runner issue that's getting masked and saying this, trying to nail it down.

**Comment by IanMitchell** [comment]
Yeah, was a test runner issue. Sorry, not that strong in python so didn't catch it earlier - apologies for the errant report! Thanks for your time
