### ISSUE TITLE
DEBUG Setting Is Never Actually Used

### ISSUE THREAD

**Issue by derekdowling** [scrapinghub/slackbot#17]
This: https://github.com/lins05/slackbot/blob/master/slackbot/settings.py#L3 setting doesn't actually do anything as far as I can tell.

**Comment by lins05** [comment]
Actually it's used here: https://github.com/lins05/slackbot/blob/d4b176fe1fea71e43e8099491d79cfdeb8c6c3e8/run.py#L13 .
