### ISSUE TITLE
I would like my bot to respond text in attachments.

### ISSUE THREAD

**Issue by andormeda-san** [scrapinghub/slackbot#180]
I would like to my bot to respond text in attachments. However, "respond_to" and "listen_to" seem to respond to plain text only.

Anyone have a good idea?

Specifically, I want to respond bot to notification from stackdriver to slack as follows.

![image](https://user-images.githubusercontent.com/43896977/47399109-09797b00-d772-11e8-9a33-ab3aca999fcc.png)

**Comment by seerickcode** [comment]
I think you would listen to / reply to everything, check for and open an attachment (if an appropriate type), then parse the contents.
I have found the the reply/listen_to will match in multiple cases, so a catch all rule would not prevent other more specific rules from running.

**Comment by andormeda-san** [comment]
thank you for your advice.
I got "message.body" as dct type as below.

@listen_to(r'[\s\S]*')
def listen_func(message):
    dct = message.body
