### ISSUE TITLE
getting a command with message then sending it to specific channel

### ISSUE THREAD

**Issue by RafaelCenzano** [scrapinghub/slackbot#184]
I was wondering how to make it so I have a command and the bot message a certain example. For example, I message the bot in a direct message or in a specific bot channel and I want it to use that message and put it in the announcements channel.

**Comment by kiaka010** [comment]
I think the only way is to access the rtm_send_message in the client
```
@respond_to('Make Announcement (.*)', re.IGNORECASE)
def make_announcement(message, text):
    message._client.rtm_send_message('GXXXXXXX', text)
```

**Comment by RafaelCenzano** [comment]
Thank you. Was able to get it done with slack webhook.
