### ISSUE TITLE
Attachment Support? https://api.slack.com/docs/attachments

### ISSUE THREAD

**Issue by kpx-dev** [scrapinghub/slackbot#27]
https://api.slack.com/docs/attachments

Does slackbot support attachments? If not, is it something I can submit a PR for?

Thanks

**Comment by kpx-dev** [comment]
@lins05 bump - is it possible?

**Comment by lins05** [comment]
Thanks for the idea. With few lines of code, I think the `reply_webapi` method of the `Message` object can be used to send replies with attachments. 

https://github.com/lins05/slackbot/blob/d4b176fe1fea71e43e8099491d79cfdeb8c6c3e8/slackbot/dispatcher.py#L129-L149

**Comment by gpailler** [comment]
You can send attachments with the following snippet

```
attachments = [
{
                'fallback': 'Fallback text',
                'author_name': 'Author',
                'author_link': 'http://www.github.com',
                'text': 'Some text',
                'color': '#59afe1'
            }
]
message.send_webapi('', json.dumps(attachments))
```

**Comment by kpx-dev** [comment]
Thanks guys! 

@gpailler your suggestion worked fine, I'll go ahead and make a doc PR to Readme
