### ISSUE TITLE
Why is this project not a fork

### ISSUE THREAD

**Issue by kenden** [scrapinghub/slackbot#28]
Why have a new project? Why is this not forked from llimllib/limbo?
https://guides.github.com/activities/forking/
A fork would allow to share fixes / features. 
Now we have 2 smaller projects, it's hard to know which to pick.

**Comment by gpailler** [comment]
We should wait the reponse from @lins05 but I checked both projects before contributing a bit on this one and I think both projects have nothing in common. I'm not sure one is a fake fork from another.
As there no code in common, it's difficult to share fixes/features

**Comment by lins05** [comment]
@kenden Good question. Though this project has borrowed things from both https://github.com/llimllib/limbo, and https://github.com/skoczen/will (the latter is an excellent chat bot for hipchat, I should list it in the README), most of the code is rewritten from scratch (as @gpailler has noticed). And you may see that llimllib/limbo provides a lot of default plugins, which I don't think is useful in my own use case.  So based on these difference,  I did't fork it but created a new repo instead.

**Comment by kenden** [comment]
Thanks. I was confused by the wording "based on" llimbo/slack in the readme. Which to me means "Slack is the base where changes could be pushed back to and pulled from". I submitted a pull request to change that.
