### ISSUE TITLE
Bot crashes because user cannot be found

### ISSUE THREAD

**Issue by larsga** [scrapinghub/slackbot#30]
This is the same issue that pull request #24 is trying to work around. The bot crashes with the following:

```
Traceback (most recent call last):
  File "amibot.py", line 61, in <module>
    main()
  File "amibot.py", line 11, in main
    bot.run()
  File "/Library/Python/2.7/site-packages/slackbot/bot.py", line 36, in run
    self._dispatcher.loop()
  File "/Library/Python/2.7/site-packages/slackbot/dispatcher.py", line 94, in loop
    self._on_new_message(event)
  File "/Library/Python/2.7/site-packages/slackbot/dispatcher.py", line 52, in _on_new_message
    username = msguser['name']
TypeError: 'NoneType' object has no attribute '__getitem__
```

The problem is with this bit of code:

```
        botname = self._client.login_data['self']['name']
        try:
            msguser = self._client.users.get(msg['user'])
            username = msguser['name']
        except KeyError:
            if 'username' in msg:
                username = msg['username']
            else:
                return
```

self._client.users doesn't contain this particular user, and so msguser['name'] gives a TypeError because msguser is none. As far as I can tell, client.users is set on login. Presumably that means that any users appearing after the bot has logged in are not known to the bot and will cause this problem.

**Comment by lins05** [comment]
We can do the following regarding this issue:

1) merge #24 to avoid the crash
2) add another thread that periodically updates the users list .

**Comment by larsga** [comment]
A cleaner alternative might be to detect when the user is not in the list and then refresh the list. That avoids the extra thread, and also avoids a workaround that might hide real bugs. But up to you.

**Comment by osteenbergen** [comment]
Just experienced this issue, however no user joined the channel after starting the bot. Probably #24 as suggested by @lins05. I agree with @larsga to update the user list on demand.

**Comment by jtatum** [comment]
The bot no longer crashes. #61 tracks the invisible users problem, something we definitely need to fix.
