### ISSUE TITLE
Handle command with params

### ISSUE THREAD

**Issue by kpx-dev** [scrapinghub/slackbot#34]
Hi guys,

I want my users to type 'stats' to get stats for last week. I also allow them passing in date time: 'stats yesterday today' to do a date range

I have this so far, but when user pass in the stats command with date range, it will execute twice since it also listen to 'stats'. Can you point out how I would allow the bot to do this?

Here's what I have: 
@respond_to('stat', re.IGNORECASE)
@respond_to('stat (._) (._)', re.IGNORECASE)
def stats(message, start_date=None, end_date=None):

Thanks

**Comment by gpailler** [comment]
Your first regex should match only stat word so something like following should work

```
@respond_to('stat$', re.IGNORECASE)
@respond_to('stat (.) (.)', re.IGNORECASE)
```

**Comment by kpx-dev** [comment]
@gpailler Thanks, it works! I'll make an PR to update the doc to handle params like this
