### ISSUE TITLE
Bot instances don't close

### ISSUE THREAD

**Issue by LarsFox** [scrapinghub/slackbot#40]
I suppose I've messed it all up, but here's the list of what I've done:
1. Installed the package, added the token
2. Added simple plugin, which simply returns "dot" when "dash" is sent
3. Launched the project from Sublime (copy+paste from readme)
4. Then I've changed my function, so it now returns "love" when "love" is sent (copy+paste from readme)
5. Launched the project from Sublime (copy+paste from readme)
6. And now bot returns 2 answers:
   - if it's "love" it sends "Bad command", then "love"
   - if it's "dash" it sends "dot", then "Bad command"
   - if it's something meaningless, it sends two "Bad command"s

I believe I made something wrong, but how to stop these instances now? Disabling-enabling the bot does not help, so I'm kinda stuck

**Comment by lins05** [comment]
I dont' use sublime, but you can always terminate a process from the task manager, be it on windows, mac or linux.
