### ISSUE TITLE
Trivial novice question... Where do I put plugins?

### ISSUE THREAD

**Issue by psychemedia** [scrapinghub/slackbot#41]
If I put the example plugin code into a file `demo.py`, and have a simple `run.py` script:

```
from slackbot.bot import Bot
def main():
    bot = Bot()
    bot.run()

if __name__ == "__main__":
    main()
```

where do I put the `demo.py` file and how do I tweak the `PLUGINS` setting?

**Comment by psychemedia** [comment]
To answer my own question, if running `run.py` in the current directory with `slackbot_settings.py` also in the current directory, putting `demo.py` into a subdirectory `demo` **along with an empty `__init__.py` file** and then adding `demo` to the list of plugins does the trick...

**Comment by kemaldarmawan** [comment]
I tried your solution but didn't work.
