### ISSUE TITLE
get username from a `slackbot.dispatcher.Message` object.

### ISSUE THREAD

**Issue by owocki** [scrapinghub/slackbot#43]
It'd be great to be able to get the message sender from the `slackbot.dispatcher.Message` object:

```
ipdb> message.
message.body          message.reply         message.send
message.channel       message.reply_webapi  message.send_webapi
```

`message.body['user']` is the closest thing I could find, but it's only a unicode ID:

```
ipdb> message.body['user']
u'U055J62L4'
```

**Comment by owocki** [comment]
Nevermind, it seems `message.channel._client.users[message.body['user']][u'name']` will get me this data.

**Comment by kevinsheehan** [comment]
Thanks for the response @owocki I hadn't realized I could get more than the unique id without hitting the API again.

**Comment by melvilgit** [comment]
@kevinsheehan  @owocki   How to get the slack message sent from the object ?

**Comment by melvilgit** [comment]
What is the message object structure for slack bot ?
