### ISSUE TITLE
Bad command "<command>", You can ask me one of the following questions:

### ISSUE THREAD

**Issue by kevinsheehan** [scrapinghub/slackbot#45]
Personally I am not a fan of this. I don't like every time one of my users mistypes a command on accident it spams the chat with the list of possible commands. I think a "help" command would be much better and would only list off possible options when that is used.

**Comment by lins05** [comment]
You can bind your help handler to the catch-all regexp, e.g. : 

``` python
@respond_to('.*')
def help(message):
    ....
```

**Comment by kevinsheehan** [comment]
Oh, that works. Thanks for the response @lins05!

**Comment by kevinsheehan** [comment]
Ah, this gets picked up even if another regex is picked up that the bot actually knows. Any suggestions or did I miss something?

**Comment by merqurio** [comment]
@lins05 Any idea on how to implement a custom default error message ? Maybe cheking if there is a fx with a specific name in the setting.py if not falling back to actual beahaviour ?
:+1:

**Comment by kevinsheehan** [comment]
Yea, @merqurio that's kind of what I was thinking.

**Comment by gregoralbrecht** [comment]
A default error message would be much appreciated!

**Comment by lins05** [comment]
Already implemented. See https://github.com/lins05/slackbot/blob/0.3.1/README.md#configure-the-default-answer .
