### ISSUE TITLE
support file uploads

### ISSUE THREAD

**Issue by jtauber** [scrapinghub/slackbot#50]
I'm writing a bot that generates images so there isn't a URL I can use in an attachment.

Does slackbot support file uploads to Slack so I can generate the image, upload it to slack for use as an attachment?

**Comment by lins05** [comment]
You can use `message.channel.upload_file` to upload a file, refer to  the [default plugins code](https://github.com/lins05/slackbot/blob/97f4f0adfab092ba61e08d42860c2f58617945d9/slackbot/plugins/upload.py#L11-L13) for an example.
