### ISSUE TITLE
PROPOSAL: Slackbot settings when bot is instanced

### ISSUE THREAD

**Issue by merqurio** [scrapinghub/slackbot#52]
We wanted to create more than a bot, different instances. Right now all the settings of the bot are defined in the `slackbot_settings.py`files, but I think that a more intuitive implementation would be to pass thos configurations as attributes of the class instantiation.

``` python
bot = Bot(api_token="<your-api-token>",
          plugins_dir="your_plugins_directory/"
          default_reply=<my_func or str>)
```

**Comment by merqurio** [comment]
I would gladly do the PR on that :+1:

**Comment by lins05** [comment]
SGTM!

**Comment by merqurio** [comment]
Great, expect a PR for next week !

**Comment by chris-skud** [comment]
Is this in motion? And to confirm, would this enable launching the bot into multiple Slack teams from single bot process? [Like Botkt's ability to spawn teams by token](https://github.com/howdyai/botkit/blob/febbd176fe6926a8211938f71b7c6217a0f90531/bot.js#L79)? 

If so, a big :+1: .

Thanks!

**Comment by merqurio** [comment]
I'm on it, and I think yes, you could be able to get two bot's but each one
on it's own thread
https://github.com/lins05/slackbot/blob/develop/slackbot/bot.py#L32 as
far as I understand, but sure @lins05 knows better than me !

**Comment by chris-skud** [comment]
thx!

**Comment by thekantian** [comment]
Just a ping here - this would be a big win to get in there for me - would be happy to help out if at all possible - is there a branch towards this feature yet?

**Comment by merqurio** [comment]
WIP, nothing clear yet, if you start a branch I'll gladly help you :grin:

**Comment by merqurio** [comment]
There it is @thekantian

**Comment by thekantian** [comment]
Wow, too fast! Will take a look @merqurio that's awesome...
