### ISSUE TITLE
Error R10 (Boot timeout) 

### ISSUE THREAD

**Issue by austinfrey** [scrapinghub/slackbot#56]
I've deployed to Heroku. The app deploys with no errors. I briefly am able to interact with the bot then...

`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

Not sure how to fix this. Any help appreciated.

**Comment by lins05** [comment]
It's rather a heroku related problem, please do you homework.

When you deploy an app on heroku, heroku expects the server to listen on a port within 60 seconds. 

https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout
