### ISSUE TITLE
Plugins modules required to be packages

### ISSUE THREAD

**Issue by uogbuji** [scrapinghub/slackbot#59]
I can't really get slackbot to work with my custom modules at all (I'm on Python 3.5) but I thought I'd document one of the major hurdles I discovered while I wrangle on. 

[The import hook code](https://github.com/lins05/slackbot/blob/develop/slackbot/manager.py#L46) is guaranteed to fail if a simple Python module is specified rather than a package. That's because `submodule_search_locations` is None in that case. If this is an intended limitation (though I can't imagine why it would be) it should be documented as such.

**Comment by uogbuji** [comment]
Actually it looks like that was the final hurdle. Once I put the custom plugins into a package I was able to get them to work, but the wart still stands.

**Comment by JaniKarh** [comment]
I am stuck on the same thing (Python 3.5.1). I cannot get my own plugins to work (`myplugins/myplugin.py`), keep getting:
`AttributeError: module 'myplugins.myplugin' has no attribute '__path__'``

Could you please walk me through, what you did to make it work?

**Comment by merqurio** [comment]
Try just 'myplugins' ; let me know if works

**Comment by janik6n** [comment]
Thanks! I deleted my message, as I resolved this just as you proposed almost immediately after posting. Sorry I was a bit hasty.

**Comment by uogbuji** [comment]
Just for anyone who comes along later, you need to make sure you have an `__init__.py` as well in the folder you specify, in order to make sure it's a proper [Python package](http://www.network-theory.co.uk/docs/pytut/Packages.html). You also need to make sure it's in your `sys.path` (e.g. by proper installation into `site-packages` or manipulating the  `PYTHONPATH` environment.

**Comment by jtatum** [comment]
This was actually fixed in #71.
