### ISSUE TITLE
New users are invisible

### ISSUE THREAD

**Issue by Resisty** [scrapinghub/slackbot#61]
I don't have a clear way to demonstrate this but using the latest version of slackbot (installed by pip on 2016-03-20), the bot fails to react to messages sent by users who joined the organization after the bot.

Example:

```
*bot will listen_to('asdf'), reply 'fdsa'
python runbot.py
*normal execution for a while*
*new_user joins*
new_user: asdf
*no response from bot*
old_user: asdf
bot: fdsa
```

**Comment by merqurio** [comment]
Hey there !
I understand then that this is something that wasn't happening to you before ?

**Comment by Resisty** [comment]
Oh, no, I just started using slack/slackbot a couple days ago. I have no idea about previous versions of slackbot.

**Comment by merqurio** [comment]
Cool :+1: I'll try to check why this is happening. Have you tried restarting the bot ?

**Comment by Resisty** [comment]
Yes, restarting is an effective workaround.

**Comment by merqurio** [comment]
Maybe as @larsga commented in #30 the users list might need a refresh.

**Comment by garyrobert** [comment]
I can also confirm that this is occurring. New user was unable to interact with the bot (DM or channel) until restarting the slackbot app.

It looks like when the app starts up, in slackclient.py it grabs active users and channels.

```
    self.users = {}
    self.channels = {}
```

**Comment by roperi** [comment]
Has anyone found a workaround for this? It looks @osteenbergen has a nice reconnect implementation.
