### ISSUE TITLE
PROPOSAL: Use python async module

### ISSUE THREAD

**Issue by merqurio** [scrapinghub/slackbot#65]
Using new python async module could be beneficial in a case like slackbot.

The [`MessageDispatcher.loop`](https://github.com/lins05/slackbot/blob/develop/slackbot/dispatcher.py#L92-L99) could be an [`@asyncio.coroutine`](https://docs.python.org/3/library/asyncio-task.html) and the main [`Bot.run`](https://github.com/lins05/slackbot/blob/develop/slackbot/bot.py#L28-L34) simply a [`loop.run_until_complete`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.run_until_complete).

Understanding that concurrency is about dealing with lots of things at same time and parallelism about doing lots of things at once, I think async coroutines are a good choice in this case. 

**Pros:**
- Non-blocking
  - Various Bots working in parallel
  - DB transaction
  - Cross-services checks (Long HTTP waits)
- Add routines that wait (#21)

**Cons:**
- Python 3.4+ only
- Rewriting code

I would love to hear your opinions on this.

**Comment by aperezalbela** [comment]
@merqurio Why did you closed this? I totally agree, but...

To avoid **Python 3.4+ only** disadvantage, it could be done using Twisted (event-driven).

**Comment by merqurio** [comment]
Sorry, We don't use slack any more.  Bests
