### ISSUE TITLE
List of plugins?

### ISSUE THREAD

**Issue by kvarga** [scrapinghub/slackbot#76]
Is there anywhere to keep a list of plugins? I'll create a Wiki page if not. 

Just made [slackbotjira](https://github.com/kvarga/slackbotjira)

**Comment by lins05** [comment]
The slackbotjira plugin is interesting! What about creating a separate markdown page to list the third party plugins, e.g. "thirdparty-plugins.md" and add a link to it in the REAME.md file?

**Comment by gpailler** [comment]
I can propose another atlassian plugin if you want to add it to the wiki page:
https://github.com/gpailler/AtlassianBot/tree/develop

**Comment by kvarga** [comment]
@lins05  - That would require commit / pull request for each module. Would be useful for "verified" plugins, but I think the Wiki (with maybe a link to the relevant Wiki page in README.md would make sense). Either way is fine with me.

**Comment by jtatum** [comment]
Wiki makes sense to me. Why not make the page and if @lins05 decides a committed file is better, we can migrate it?

**Comment by kvarga** [comment]
Created: https://github.com/lins05/slackbot/wiki/Plugins
