### ISSUE TITLE
Better visualization of tables in slackbot integration

### ISSUE THREAD

**Issue by arunviswanath** [scrapinghub/slackbot#77]
Other visualizations get reproduced in Slack as is. Tables, on the other hand, are sent to Slack as the underlying data, with fields separate by hyphens.  This makes tables with multiple columns not-so-readable via Slack.

**Comment by jtatum** [comment]
Slack supports sending tables via attachments. Slackbot supports attachments in message.send_webapi (and when #75 is merged, in message.reply_webapi). Slack's documentation and a handy interactive preview tool is at https://api.slack.com/docs/attachments

Note that attachments come in as a list of dicts, so you might do something like this in a slackbot plugin:

``` python
attachments = [{
    'fallback': 'A textual representation of your table data',
    'fields': [
        {
            'title': 'field1',
            'value': 'data1',
            'short': True
        },
        {
            'title': 'field2',
            'value': 'data2',
            'short': True
        }
    ]
}]
message.send_webapi('', attachments=attachments)
```

This is what that looks like in the tester:
![screen shot 2016-04-19 at 2 04 40 pm](https://cloud.githubusercontent.com/assets/340001/14655568/c365cdd4-0637-11e6-8444-d7e9ebebb1be.png)

**Comment by arunviswanath** [comment]
Thank you--we'll try it out!

On Tue, Apr 19, 2016 at 5:05 PM, James Tatum notifications@github.com
wrote:

> Slack supports sending tables via attachments. Slackbot supports
> attachments in message.send_webapi (and in the unreleased version on
> develop, message.reply_webapi). Slack's documentation and a handy
> interactive preview tool is at https://api.slack.com/docs/attachments
> 
> Note that attachments come in as a list of dicts, so you might do
> something like this in a slackbot plugin:
> 
> attachments = [{
>     'fallback': 'A textual representation of your table data',
>     'fields': [
>         {
>             'title': 'field1',
>             'value': 'data1',
>             'short': True
>         },
>         {
>             'title': 'field2',
>             'value': 'data2',
>             'short': True
>         }
>     ]
> }]
> message.send_webapi('', attachments=attachments)
> 
> This is what that looks like in the tester:
> [image: screen shot 2016-04-19 at 2 04 40 pm]
> https://cloud.githubusercontent.com/assets/340001/14655568/c365cdd4-0637-11e6-8444-d7e9ebebb1be.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lins05/slackbot/issues/77#issuecomment-212129609

## 

Arun Viswanath, Business Analyst
_Q_ | managedbyq.com | c: 201.362.4724 | @managedbyq
https://twitter.com/ManagedbyQ

**Comment by Tibingeo** [comment]
How can I do `field3` next to `filed2`. I basically wanted 3 columns in one row.

**Comment by davidnewhall** [comment]
make the fields smaller.

**Comment by dialupdisaster** [comment]
I think 2 wide is a limitation set by Slack itself not this library @Tibingeo

**Comment by hkedia321** [comment]
Any idea how we can make it three columns in a row?

**Comment by dialupdisaster** [comment]
Like I said in the comment just above yours it looks like a limitation with Slack itself and not something this chatbot can control...

Here is the documentation from slack:

https://api.slack.com/docs/message-attachments#fields

```
An optional flag indicating whether the value is short enough to be displayed side-by-side with other values.
```
Which leads me to believe side-by-side means only ever 2 wide.
