### ISSUE TITLE
Bot not responding on a Linux machine, but does on Windows

### ISSUE THREAD

**Issue by Paradoxis** [scrapinghub/slackbot#85]
I wrote a bot for my company's slack channel, and it works fine if I run it locally on my Windows machine. However, whenever I run it on a live linux server I get the following error message:

```
No handlers could be found for logger "slackbot.manager"
```

After that the bot simply ignores all input in plugins that were loaded, and when I run the same code on Windows, I do get a reply.

My **run.py** file:

```
from slackbot.bot import Bot


def main():
    """
    Main entry point of the application
    :return: void
    """
    bot = Bot()
    bot.run()


# Run if main
if __name__ == "__main__":
    main()
```

My **slackbot_settings.py** file:

```
print("Loaded settings")

API_TOKEN = "secret"
ERRORS_TO = 'luke'
PLUGINS = [
    'plugins.trains.departures'
]
```

My plugin **plugins/trains/departures.py** _(all directories have __ init __.py files in them)_:

```
from re import IGNORECASE
from slackbot.bot import listen_to

@listen_to("foo", IGNORECASE)
def foo(bot):
    bot.reply("bar")
```

**Comment by yourbuddyconner** [comment]
I'm getting the same issue, however I'm running it on a Mac. Seems like it could be missing logging dependencies, but I can't imagine what. Digging into the code to figure it out now.

**Comment by Paradoxis** [comment]
@yourbuddyconner <strike>found out what it was yet? I'm having the same issue again</strike> 

Found out the cause of the issue, there was an import error in my script which didn't get displayed. Fixed it by intsalling the `logging` module and adding the following code in **run.py** before calling `bot.run()`

```
$ pip install logging
```

Then in **run.py**

```
import logging
logging.basicConfig()
```

**Comment by todd-alexion** [comment]
Can this issue be closed?
