### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by goldfish911** [scrapinghub/slackbot#88]
"First create a slackbot_settings.py and a run.py in your own instance of slackbot."
I'm trying to understand this documentation to set up my own 'instance' of slackbot. But I do not understand what these instructions want me to do? I tried making two files 'slackbot_settings.py' and 'run.py' in the same folder , but I feel that's not how this works.

Could someone please clarify?

**Comment by KevinHu2014** [comment]
@goldfish911 
Did you figure it out?
I'm also confused.
Need some help.
